app:
  context: /catpro
  name: catpro
  title: MG's Blog
  secret: 5e04c0bc-b220-5076-bbdd-aaba3f8de881
  key: 4d03c0bcb2204064aabbaaba3f8dd987
  iv: 5d02c0ecb1206065
  alg: aes-256-cbc
  db:
    dialect: mysql
    database: catpro
    host: localhost
    username: root
    password: root
    port: 3306
    dialectOptions:
      charset: utf8mb4
    define:
      underscored: false
      underscoredAll: false
      charset: utf8
      timestamps: true
